### ISSUE TITLE
Append information

### ISSUE THREAD

**Issue by cre8** [tno-ssi-lab/wallet-overview#5]
I would love to have two more information for the table:

Is the wallet cloud based or edge based. In case of organization based wallets I would prefer a cloud one. Or maybe even as a human being I prefer a cloud one with for example confidential computing.

Another point would be links to the projects, especially when they are open source

Great work @maaikevanleuken and your team! :)

**Comment by maaikevanleuken** [comment]
Thanks @cre8 for your suggestions. This issue will be resolved once [PR3](https://github.com/tno-ssi-lab/wallet-overview/pull/3) is resolved.

**Comment by cre8** [comment]
There are solutions to run a docker container in a confidential computing environment, see https://kubernetes.io/blog/2023/07/06/confidential-kubernetes/ I don't know any specific wallet that is advertising to have build in confidential computing, but with this approach every cloud wallet should work with this with solutions like this: https://github.com/edgelesssys/constellation
